VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "IVbaDIFunc"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
'@IgnoreModule ParameterNotUsed
'@Folder "VbaDI"
Option Explicit

Public Function Predicate(ByVal pVal As Variant, ByVal pIndex As Variant, ByVal pColl As Collection) As Boolean
End Function

Public Function MapFunc(ByVal pVal As Variant, ByVal pIndex As Long, ByVal pColl As Collection) As Variant
End Function

Public Function ValueKeyPredicate(ByVal pVal As Variant, ByVal pKey As Variant) As Variant
End Function

