VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "IVbaDIFunc"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
'@IgnoreModule ParameterNotUsed
'@Folder "VbaDI"
Option Explicit

Public Function Predicate(ByVal pVal As Variant, ByVal pIndex As Long, ByVal pColl As Collection) As Boolean
End Function

Public Function PredicateValueAndKey(ByVal pValue As Variant, ByVal pKey As String) As Boolean
End Function

Public Function MapFunc(ByVal pVal As Variant, ByVal pIndex As Long, ByVal pColl As Collection) As Variant
End Function

'Public Function ValueFunc(ByVal pVal As Variant) As Variant
'End Function

